language: node_js
sudo: required
notifications:
  slack:
    secure: "AcZJC9OsZAsAUqQV6bBEhvCwhwgVIsGuTQbsUSioSHJ6uNRdUSfSHV710wbzru2f5BADGGRFyXpsiYr3uGEa0wK/DC9Y68G+uC4slHF3+IejT8vmHrKIH1RabbcErQSUxK0y6TVWzWYfhqu3Bx7Nj9cGJaUMjyMM1F6Ao0uQvnbNCqdEVGRSHYKFm4+V1U4AIZH4fVWZI8T/D1UXey4Gaf0eFj91UMgh+B8pKs2aKl4MfGcHUwGjmRt0hl3WKylFdyjizQUojYiSO+smi4zl2imEhRW+XNgx/lhITrd1zYl/d2pWy8Qxa7qzQzv6jg4OPo1kCy3SEvio28EvUcMJTxMOwPnYRjptNiD+PijF4NuW4aFCjuNpMxoBTX+wz9EwzWvpmd48p6z25F63w0x5saeDEjiy0uOEwYg9EQvpPxVUhwx40abxHms1JegxE1PZg2aRkMWqtsWZouK1Pehz/6i9IgT0tqkaozQdhYn3B4dYryzCufRqsL3Rkp6YWGFTvwKKZN9Vq7PeLeiD9wprD5KqHS/aFihZC2zApDQAFeaPfNlAq2Ib6QmZwi2ts/FMbJLDm2WhbjGVE3Jbl6zix+tJCbmjPcUJaxybHye1AS/I8kUkTwkZ2ujD5l1tPB7gexAaRtZt4O6fIHW/wXH5cxdeumWnLed2GN94w3v93Os="
node_js:
    - '0.12'
env:
    - JASMINE_SERVER_UNIT=0 JASMINE_SERVER_INTEGRATION=1 JASMINE_CLIENT_UNIT=1 JASMINE_CLIENT_INTEGRATION=1 JASMINE_BROWSER=PhantomJS
branches:
  except:
    - release-dev
    - release-prd
before_install:
    - "curl https://install.meteor.com/ | sh"
    - npm install -g gulp
    # - npm install -g velocity-cli
before_script:
    - gulp lint
script:
    # - ( cd src && velocity test-app --ci ) # Killing test run on CI until timeout issue is resolved
    # https://github.com/xolvio/meteor-jasmine/issues/324
after_success:
    - bash release.sh
