language: node_js
sudo: required
notifications:
  slack: retrospectre:DT9bWKb0zenFvq6umddlg0ko
node_js:
    - '0.12'
env:
    - JASMINE_SERVER_UNIT=0 JASMINE_SERVER_INTEGRATION=1 JASMINE_CLIENT_UNIT=1 JASMINE_CLIENT_INTEGRATION=1 #WORKING_DIR="src/"" TEST_COMMAND="meteor --test"
branches:
  except:
    - release-dev
    - release-prd
before_install:
    - "curl https://install.meteor.com/ | sh"
    # - "curl -L http://git.io/ejPSng | /bin/sh"
before_script:
    - gulp lint
script:
    - ( cd src && meteor --test )
after_success:
    - bash release.sh
