language: node_js
notifications:
  slack: retrospectre:DT9bWKb0zenFvq6umddlg0ko
node_js:
- '0.12'
branches:
  except:
    - release-dev
    - release-prd
before_script:
    - gulp lint
after_success:
    - bash release.sh
